name: ROVER
root: ~/URC
windows:
  -  TX1: cat README.md; cat rosws/README.md
  -  TOP: 
      layout: tiled
      panes:
        - top
        - htop
        - dmesg -w
        - watch "./scripts/print_cpu_temp.sh; df -h"
  - CORE: 
      layout: even-horizontal
      panes:
        - 
        - roscore
  - GPS:
      root: ~/URC/rosws/src/rover/
      layout: even-horizontal
      panes:
        - sleep 5; roslaunch rover gps.launch
        - sleep 3; rostopic echo /gps/fix
        - sleep 3; rostopic echo /gps/filtered
  - IMU:
      root: ~/URC/rosws/src/rtimulib_ros/
      layout: even-horizontal
      panes:
        - sleep 4; roslaunch rtimulib_ros rtimulib_ros.launch
        - sleep 3; rostopic echo imu/data_raw
        - sleep 3; python ./src/imu_fixer.py
  - RTAB:
      root: ~/URC/rosws/src/rover_navigation/
      layout: titled
      panes:
        - sleep 5; roslaunch rover_navigation rtabmap.launch
        - sleep 5; roslaunch rover_navigation move_base.launch
        - sleep 5; rostopic echo /cmd_vel_mux/move_base
  - SCI:
      root: ~/URC/rosws/src/rover_science/
      layout: tiled
      panes:
        - 
        - python ~/URC/devstuff/components/ImageOverlay/overlay_scale_and_compass.py
        - sleep 3; rosrun rover_science save_temp.py _description:=site1
        - sleep 3; rosrun rover_science save_ph.py _description:=site1
        - watch cat *_temperature.txt
        - watch cat *_ph.txt
  - USB:
      root: ~/URC/rosws/src/rover/
      layout: main-horizontal
      panes:
        - sleep 4; roslaunch rover usb_webcams.launch
        - 
  - ZED:
      root: ~/URC/rosws/src/rover/
      layout: even-horizontal
      panes:
        - sleep 5; roslaunch rover zed_up.launch
        - sleep 4; roslaunch rover_navigation rgbd_odometry.launch
  - EKF:
      root: ~/URC/rosws/src/rover_robot_localization/
      layout: tiled
      panes:
        - sleep 4; roslaunch rover_robot_localization global_ekf.launch
        - sleep 3; rostopic echo /odometry/filtered_global
        - sleep 3; rostopic echo /gps/filtered
        - sleep 3; rosrun tf tf_echo odom robot_base
  - D:
  - M:
  - A:
  - H:
