name: ROVER
root: ~/URC
windows:
  -  TX1: cat README.md; cat rosws/README.md
  -  TOP: 
      layout: tiled
      panes:
        - top
        - htop
        - dmesg -w
        - cmatrix
  - CORE: 
      layout: even-horizontal
      panes:
        - bash
        - roscore
  - GPS:
      layout: even-horizontal
      panes:
        - sleep 3; rosrun nmea_navsat_driver nmea_serial_driver _port:=/dev/ttyTHS2 _baud:=9600
        - sleep 3; rostopic echo fix
  - IMU:
      layout: even-horizontal
      panes:
        - sleep 3; roslaunch rtimulib_ros rtimulib_ros.launch
        - sleep 3; rostopic echo imu/data_fixed
        - sleep 3; python ./rosws/src/rover_robot_localization/src/imu_fixer.py
  - RTAB:
      layout: even-horizontal
      panes:
        - "#roslaunch rover_navigation rtabmap.launch"
        - "#roslaunch rover_navigation move_base.launch"
  - SCI:
      layout: tiled
      panes:
        - bash
        - python ~/URC/devstuff/components/ImageOverlay/overlay_scale_and_compass.py
        - sleep 3; rosrun rover_science save_temp.py _description:=site1
        - sleep 3; rosrun rover_science save_ph.py _description:=site1
        - watch cat *_temperature.txt
        - watch cat *_ph.txt
  - USB:
      layout: main-horizontal
      panes:
        - sleep 3; roslaunch rover usb_cameras.launch
        - bash
  - ZED:
      layout: even-horizontal
      panes:
        - sleep 3; roslaunch rover zed_up.launch
        - bash
  - EKF:
      layout: even-horizontal
      panes:
        - sleep 3; rostopic echo odometry/filtered
        - sleep 3; roslaunch ./rosws/src/rover_robot_localization/launch/dual_ekf.launch
  - D:
  - M:
  - A:
  - H:
