# sudo apt install tmuxinator
name: ROVER
root: ~/URC
windows:
  -  TX1: cat README.md; cat rosws/README.md
  -  TOP: 
      layout: tiled
      panes:
        - top
        - htop
        - dmesg -w
        - watch "./scripts/print_cpu_temp.sh; df -h"
  - CORE: 
      layout: even-horizontal
      panes:
        - 
        - roscore
  - GPS:
      root: ~/URC/rosws/src/rover/
      layout: even-horizontal
      panes:
        - sleep 5; roslaunch rover gps.launch dev:=/dev/ttyTHS2
        - sleep 3; rostopic echo /gps/fix
        - sleep 3; rostopic echo /gps/filtered
  - IMU:
      root: ~/URC/rosws/src/rtimulib_ros/
      layout: even-horizontal
      panes:
        - sleep 4; roslaunch rtimulib_ros rtimulib_ros.launch
        - sleep 3; rostopic echo imu/data_raw
        - sleep 3; roslaunch /home/ubuntu/URC/devstuff/dan/IMU/imu_madgwick_filter.launch
        - sleep 3; rostopic echo /imu/data_madg
  - RTAB:
      root: ~/URC/rosws/src/rover_navigation/
      layout: tiled
      panes:
        - sleep 5; roslaunch rover_navigation rtabmap.launch
        - sleep 5; roslaunch rover_navigation move_base.launch
        - sleep 5; rostopic echo /cmd_vel_mux/move_base
        - sleep 5; rostopic echo /move_base/status
  - SCI:
      root: ~/URC/rosws/src/rover_science/
      layout: tiled
      panes:
        - 
        - python ~/URC/devstuff/components/ImageOverlay/overlay_scale_and_compass.py
        - sleep 3; rosrun rover_science save_temp.py _description:=site1
        - sleep 3; rosrun rover_science save_ph.py _description:=site1
        - watch cat *_temperature.txt
        - watch cat *_ph.txt
  - WEBCAMS:
      root: ~/URC/rosws/src/rover/
      layout: main-horizontal
      panes:
        - sleep 4; roslaunch rover usb_webcams.launch
        - v4l2-ctl --list-devices
  - ZED:
      root: ~/URC/rosws/src/rover/
      layout: even-horizontal
      panes:
        - sleep 5; roslaunch rover zed_up.launch
        - sleep 4; roslaunch rover_navigation rgbd_odometry.launch
#  - EKF:
#      root: ~/URC/rosws/src/rover_robot_localization/
#      layout: tiled
#      panes:
#        - sleep 4; roslaunch rover_robot_localization global_ekf.launch
#        - sleep 3; rostopic echo /odometry/filtered_global
#        - sleep 3; rostopic echo /gps/filtered
#        - sleep 3; rosrun tf tf_echo odom robot_base
  - ARM:
      root: ~/URC/rosws/src/rover_arm/
      layout: tiled
      panes:
        - "#rosrun rover_arm simple_arm_serial.py"
  - DRIVE:
      root: ~/URC/rosws/src/rover_drive/
      layout: tiled
      panes:
        - "#roslaunch rover_drive drive.launch dev:=/dev/serial/by-id/usb-Arduino_Arduino_Due-if00"
        - "#pio run -t upload"
        - sleep 5; rostopic echo cmd_vel
        - sleep 5; rostopic echo cmd_vel_tank
  - D:
  - M:
  - A:
  - H:

