name: ROVER
root: ~/URC
windows:
  -  TX1: cat README.md; cat rosws/README.md
  -  TOP: 
      layout: tiled
      panes:
        - top
        - htop
        - dmesg -w
        - cmatrix
  - CORE: 
      layout: even-horizontal
      panes:
        - bash
        - roscore
  - GPS:
      layout: even-horizontal
      panes:
        - sleep 5; roslaunch rover gps.launch
        - sleep 3; rostopic echo /gps/fix
  - IMU:
      layout: even-horizontal
      panes:
        - sleep 5; roslaunch rtimulib_ros rtimulib_ros.launch
        - sleep 3; rostopic echo imu/data_fixed
        - sleep 3; python ./rosws/src/rover_robot_localization/src/imu_fixer.py
  - RTAB:
      layout: even-horizontal
      panes:
        - "#roslaunch rover_navigation rtabmap.launch"
        - "#roslaunch rover_navigation move_base.launch"
  - SCI:
      layout: tiled
      panes:
        - bash
        - python ~/URC/devstuff/components/ImageOverlay/overlay_scale_and_compass.py
        - sleep 3; rosrun rover_science save_temp.py _description:=site1
        - sleep 3; rosrun rover_science save_ph.py _description:=site1
        - watch cat *_temperature.txt
        - watch cat *_ph.txt
  - USB:
      layout: main-horizontal
      panes:
        - sleep 3; roslaunch rover usb_cameras.launch
        - bash
  - ZED:
      layout: even-horizontal
      panes:
        - sleep 5; roslaunch rover zed_up.launch
        - sleep 3; roslaunch rover_navigation rgbd_odometry.launch
  - EKF:
      layout: even-horizontal
      panes:
        - sleep 3; roslaunch ./rosws/src/rover_robot_localization/launch/dual_ekf.launch
        - sleep 3; rostopic echo /odometry/filtered_local
  - D:
  - M:
  - A:
  - H:
