name: BASE
root: ~/URC
windows:
  -  TX1: cat README.md; cat rosws/README.md
  -  TOP: 
      layout: tiled
      panes:
        - sudo nethogs `nmcli dev status | grep ens38 | cut -f1 -d' '`
        - htop
        - dmesg -w
        - watch -n 3 ps -ef
  - RTAB:
      layout: even-horizontal
      panes:
        - "#roslaunch rover_rtabmap_config mapping_rviz.launch"
        - "#roslaunch rover_rtabmap_config navigation.launch"
  - SCI:
      layout: tiled
      panes:
        - bash
        - python ~/URC/devstuff/components/ImageOverlay/overlay_scale_and_compass.py
        - sleep 3; rosrun rover_science save_temp.py _description:=site1
        - sleep 3; rosrun rover_science save_ph.py _description:=site1
        - watch cat *_temperature.txt
        - watch cat *_ph.txt
  - USB:
      layout: main-horizontal
      panes:
        - "#rqt --perspective-file URC/devstuff/dan/gui_configs/rqt_all_cameras.perspective"
  - ZED:
      layout: even-horizontal
      panes:
        - "#rqt --perspective-file URC/devstuff/dan/gui_configs/rqt_all_cameras.perspective"
  - RQT:
      layout: tiled
      panes:
        - rqt_graph
        - rosrun rqt_tf_tree rqt_tf_tree
        - 

