name: BASE
root: ~/URC
windows:
  -  R3: cat README.md; cat rosws/README.md
  -  TOP: 
      layout: tiled
      panes:
        - "#top"
        - htop
        - dmesg -w
        - "#cmatrix"
  - SCI:
      root: ~/URC/rosws/src/rover_science/
      layout: tiled
      panes:
        - bash
        - python ~/URC/devstuff/components/ImageOverlay/overlay_scale_and_compass.py
        - sleep 3; rosrun rover_science save_temp.py _description:=site1
        - sleep 3; rosrun rover_science save_ph.py _description:=site1
        - watch cat *_temperature.txt
        - watch cat *_ph.txt
  - CAMERAS:
      layout: main-horizontal
      panes:
        - "#rqt_image_view /camera/rgb_fixed/compressed" # Zed Left Camera
        - "#rqt --perspective-file URC/devstuff/dan/gui_configs/rqt_all_cameras.perspective" # USB Cameras
  - RQT:
      layout: tiled
      panes:
        - rosrun rqt_tf_tree rqt_tf_tree
        - rqt_graph
  - RVIZ:
      layout: tiled
      panes:
        - "#rviz"
        #- "#roslaunch rover_rtabmap_config mapping_rviz.launch"
        #- "#roslaunch rover_robot_localization odom_debug_rviz.launch"
  - MAPVIZ:
      root: ~/URC/devstuff/dan/mapping/
      layout: tiled
      panes:
        - "#roslaunch ./mapviz.launch"
        - sudo docker run -p 8080:8080 -d -t -v ~/mapproxy:/mapproxy danielsnider/mapproxy
  - RTABMAPVIZ:
      root: ~/URC/rosws/src/rover_navigation/
      layout: tiled
      panes:
        - "#roslaunch rover_navigation rtabmapviz.launch"
  - ARM:
      root: ~/URC/rosws/src/rover_arm/
      layout: tiled
      panes:
        - "#roslaunch rover_arm mimic_gazebo.launch"
  - TELEOP:
      root: ~/URC/rosws/src/rover_teleoperation/
      layout: tiled
      panes:
        - "roslaunch rover_teleoperation joy_teleoperation.launch"
  - WAYPOINT:
      root: ~/URC/rosws/src/rover/src/
      layout: tiled
      panes:
        - "python follow_waypoints.py"
        - "#rostopic pub /path_ready std_msgs/Empty -1"
        - "#rostopic pub -1 /move_base/cancel actionlib_msgs/GoalID -- {}"
  - GO2GPS:
      root: ~/URC/rosws/src/rover/src/
      layout: tiled
      panes:
        - "#python gps_goal.py --lat 43.659055 --long -79.3803416667"
        - "#rostopic pub -1 /move_base/cancel actionlib_msgs/GoalID -- {}"
