name: BASE
root: ~/URC
windows:
  -  R3: cat README.md; cat rosws/README.md
  -  TOP: 
      layout: tiled
      panes:
        - "#top"
        - htop
        - dmesg -w
        - "#cmatrix"
  - SCI:
      root: ~/URC/rosws/src/rover_science/
      layout: tiled
      panes:
        - bash
        - python ~/URC/devstuff/components/ImageOverlay/overlay_scale_and_compass.py
        - sleep 3; rosrun rover_science save_temp.py _description:=site1
        - sleep 3; rosrun rover_science save_ph.py _description:=site1
        - watch cat *_temperature.txt
        - watch cat *_ph.txt
  - CAMERAS:
      layout: main-horizontal
      panes:
        - "#rqt_image_view /camera/rgb_fixed/compressed" # Zed Left Camera
        - "#rqt --perspective-file URC/devstuff/dan/gui_configs/rqt_all_cameras.perspective" # USB Cameras
  - RQT:
      layout: tiled
      panes:
        - rosrun rqt_tf_tree rqt_tf_tree
        - rqt_graph
  - RVIZ:
      layout: tiled
      panes:
        - "#rviz"
        #- "#roslaunch rover_rtabmap_config mapping_rviz.launch"
        #- "#roslaunch rover_robot_localization odom_debug_rviz.launch"
  - MAPVIZ:
      root: ~/URC/devstuff/dan/mapping/
      layout: tiled
      panes:
        - "#roslaunch ./devstuff/dan/mapping/mapviz.launch"
        - sudo docker run -p 8080:8080 -d -t -v ~/mapproxy:/mapproxy danielsnider/mapproxy

