global_costmap:
  plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}

  robot_base_frame: robot_base
  global_frame: map
  update_frequency: 1
  publish_frequency: 0.5
  static_map: true

  inflation:
    inflation_radius: 0.07
