local_costmap:
  plugins:
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
  # assuming receiving a cloud from rtabmap_ros/obstacles_detection node

  global_frame: odom
  robot_base_frame: robot_base
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.025
  origin_x: -2.0
  origin_y: -2.0
  obstacles:
    publish_voxel_map: true
    observation_sources: point_cloud_sensor

    point_cloud_sensor: {
      sensor_frame: robot_base,
      data_type: PointCloud2,
      topic: "/zed/point_cloud/cloud_registered",
      expected_update_rate: 0.5,
      marking: true,
      clearing: true,
      min_obstacle_height: -99999.0,
      max_obstacle_height: 99999.0}
